version: '3.8'  # Define the version of Docker Compose being used.

services:  # Define the services to be created by Docker Compose.
  html-app:  # Name of the service.
    build: .  # Build the Docker image from the Dockerfile in the current directory.
    container_name: html-app-container  # Name of the container when running.
    ports:  # Mapping the container's ports to the host machine's ports.
      - "5002:80"  # Map port 5002 on the host machine to port 80 in the container.
    restart: always  # Always restart the container if it stops unexpectedly.
