version: '3.8'  # Define the version of Docker Compose being used.

services:  # Define the services to be created by Docker Compose.
  nodejs-app:  # Name of the service.
    build: .  # Build the Docker image from the Dockerfile in the current directory.
    container_name: nodejs-app-container  # Name of the container when running.
    ports:  # Mapping the container's ports to the host machine's ports.
      - "5003:3000"  # Map port 5003 on the host machine to port 3000 in the container.
    restart: always  # Always restart the container if it stops unexpectedly.
